# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1bd4685d-39a0-4483-99ed-1854e5dd23a5";
    fsType = "btrfs";
    options = ["subvol=root"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D7EE-73B2";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/1bd4685d-39a0-4483-99ed-1854e5dd23a5";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/1bd4685d-39a0-4483-99ed-1854e5dd23a5";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/2c3672bc-2d7a-4d48-b3c1-76c5e426b656";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
