[editor]
auto-format = true
auto-save = true
bufferline = "always"
color-modes = true
cursorline = true
end-of-line-diagnostics = "hint"
line-number = "relative"
rulers = [120]
scrolloff = 15

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.gutters.line-numbers]
min-width = 2

[editor.indent-guides]
character = "·"
render = true
skip-levels = 1

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true
wrap-indicator = "↩ "

[editor.statusline]
left = ["mode", "spacer", "spinner"]
center = ["file-modification-indicator", "file-name", "read-only-indicator"]
right = [
  "diagnostics",
  "file-encoding",
  "position",
  "separator",
  "total-line-numbers",
]
separator = "|"

[editor.statusline.mode]
normal = "normal"
insert = "insert"
select = "select"


[keys.normal.space]
S-tab = ":buffer-previous"
f = "file_picker"
i = ":toggle lsp.display-inlay-hints"
q = ":q"
space = ":fmt"
tab = ":buffer-next"
w = ":w"
