[main]
dpi-aware=no
# font=JetbrainsMono Nerd Font:size=12
initial-color-theme=dark
pad=30x30 center-when-maximized-and-fullscreen

[mouse]
hide-when-typing=yes

[cursor]
blink=yes
blink-rate=1000
style=beam
