name: check

on:
  push:

env:
  NIX_CONFIG: "extra-experimental-features = nix-command flakes pipe-operators"

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: flake check
        run: nix flake check

      - name: format check
        run: nix run nixpkgs#alejandra -- --check .
